Repository common-voice/common-voice, pull requests merged in 2025-06, with the labels that each got.

#4896 Update config-helper to ignore non-existent config.json
  server/src/config-helper.ts
Labels: Docker

#4931 1157- Backend to retrieve sentences & clips without variant when variant ones run out
  server/src/lib/api.ts
  server/src/lib/bucket.ts
  server/src/lib/clip.ts
  server/src/lib/model.ts
  server/src/lib/validation/clips.ts
  server/src/lib/validation/sentences.ts
  web/src/services/api.ts
Labels: Enhancement, backend

#4944 1173-MCV Fix: Use Redis to keep recorded "sentence_id"s per user
  server/src/lib/lazy-cache.ts
  server/src/lib/model/db.ts
Labels: Bug, backend
